-- Formulario de contacto: permisos y RLS en web.contacto, y web.leads_senior al esquema archivo.
-- Aplicar en el Supabase propio (supabase.xpertauth.com), en una sola transacción. No borra datos.
-- Después de aplicar: NOTIFY pgrst, 'reload schema';

-- 1. web.contacto: solo el servidor (service_role) escribe y lee; el navegador no accede.
--    Hasta ahora no tenía ningún permiso, por lo que el INSERT del servidor fallaba.
alter table web.contacto enable row level security;      -- sin políticas: anon y authenticated, nada
revoke all on web.contacto from public, anon, authenticated;
grant select, insert, update on web.contacto to service_role;

-- 1b. web.contacto.id es bigint NOT NULL sin identidad ni valor por defecto: ningún INSERT sin id
--     funcionaría ni con permisos. La tabla está vacía; se le añade identidad automática.
alter table web.contacto alter column id add generated by default as identity;

-- 2. web.leads_senior es de la formación senior (irá en la web social): al archivo, sin borrar nada.
alter table web.leads_senior set schema archivo;
comment on table archivo.leads_senior is 'Archivo de la web antigua, sin uso';

-- Deshacer (no forma parte de la migración):
--   alter table archivo.leads_senior set schema web;
--   revoke all on web.contacto from service_role;  alter table web.contacto disable row level security;
